dist: xenial
language: ruby
rvm:
  - 2.5.5
cache:
  bundler: true
install:
  - bundle
before_script:
  - rake db:setup
script:
  - bundle exec rspec
  - bundle exec rubocop --safe-auto-correct
services:
  - postgresql
  - xvfb
